---

ansible_user: Administrator
ansible_password: jVMijRwLbI02gFCo2xkjlZ9lxEA7bm7zgg==

#
# psrp specfic vars
#

ansible_connection: psrp
ansible_psrp_auth: basic
ansible_psrp_cert_validation: ignore

...
