---

- name: Create windows domain group
  win_domain_group:
    name:       "{{ user.group_name }}"
    scope:      "{{ user.group_scope }}"
    state:      "{{ user.state | default('present') }}"
  loop: "{{ active_directory_users }}"
  loop_control:
    loop_var: user

- name: Manage Active Directory users
  win_domain_user:
    name:       "{{ user.name }}"
    firstname:  "{{ user.firstname }}"
    surname:    "{{ user.surname }}"
    password:   "{{ user.password }}"
    groups:     "{{ user.group_name }}"
    state:      "{{ user.state | default(active_directory_user_state) | default('present') }}"
    email:      "{{ user.name }}@ad1.{{ GUID }}.example.opentlc.com"
  loop: "{{ active_directory_users }}"
  loop_control:
    loop_var: user

...
